# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_owner_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='numeroContacto',
            field=models.CharField(max_length=500),
        ),
    ]
