# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20180426_1939'),
        ('usuarios', '0006_arrendatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendatario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Arrendatario',
        ),
    ]
