# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20180426_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Usuario',
        ),
    ]
