# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20180426_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ciudad'),
            preserve_default=False,
        ),
    ]
