# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20180502_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=1, upload_to='imagenes/owners'),
            preserve_default=False,
        ),
    ]
