# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosParaArrendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField()),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=500)),
                ('resumen', models.CharField(max_length=500)),
                ('foto', models.ImageField(null=True, upload_to='imagenes/libros')),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'disponible'), ('quierenArrendarlo', 'quierenArrendarlo'), ('arrendado', 'arrendado')], max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Owner')),
            ],
        ),
    ]
