# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_arrendatario'),
        ('libros', '0002_auto_20180426_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArriendoDeLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField()),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Arrendatario')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.LibrosParaArrendar')),
            ],
        ),
    ]
