# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_arriendodelibro_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendodelibro',
            name='fechaFinalArriendo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='arriendodelibro',
            name='fechaInicioArriendo',
            field=models.DateTimeField(null=True),
        ),
    ]
