# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20180427_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librosparaarrendar',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('quierenArrendarlo', 'Quieren arrendarlo'), ('arrendado', 'Arrendado')], default='disponible', max_length=500),
        ),
    ]
