# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_auto_20180427_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librosparaarrendar',
            name='foto',
            field=models.ImageField(default=1, upload_to='imagenes/libros'),
            preserve_default=False,
        ),
    ]
